// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQJ9jL1jsBFXUr2nnOl9r28WkBDL64so8',
    appId: '1:1077665653460:web:ff48aac22b02f538039141',
    messagingSenderId: '1077665653460',
    projectId: 'onam-e2b3f',
    authDomain: 'onam-e2b3f.firebaseapp.com',
    storageBucket: 'onam-e2b3f.appspot.com',
    measurementId: 'G-3LC2HD9P4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QE-_lrod16gz-KtYJmiUDv8NNS7exmU',
    appId: '1:1077665653460:android:278f9bf88fb6485b039141',
    messagingSenderId: '1077665653460',
    projectId: 'onam-e2b3f',
    storageBucket: 'onam-e2b3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD078lkIHdubmX5IEqubL2VlBqmps7slIo',
    appId: '1:1077665653460:ios:bf7835e12215ab9f039141',
    messagingSenderId: '1077665653460',
    projectId: 'onam-e2b3f',
    storageBucket: 'onam-e2b3f.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQJ9jL1jsBFXUr2nnOl9r28WkBDL64so8',
    appId: '1:1077665653460:web:46376053ff48856c039141',
    messagingSenderId: '1077665653460',
    projectId: 'onam-e2b3f',
    authDomain: 'onam-e2b3f.firebaseapp.com',
    storageBucket: 'onam-e2b3f.appspot.com',
    measurementId: 'G-WH0Y29RTD3',
  );
}
